"""modelo inicial

Revision ID: 228a0066ed6f
Revises: 
Create Date: 2026-06-16 16:42:16.235162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228a0066ed6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anios_escolares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estudiantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('identificacion', sa.String(length=30), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('M', 'F', 'OTRO', name='genero'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'PROFESOR', 'PADRE', name='rol_usuario'), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('cargos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('anio_escolar_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('MATRICULA', 'MENSUALIDAD', 'MATERIAL', 'OTRO', name='tipo_cargo'), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mes_correspondiente', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'VENCIDO', 'ANULADO', name='estado_cargo'), nullable=False),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiantes_acudientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('acudiente_id', sa.UUID(), nullable=False),
    sa.Column('parentesco', sa.Enum('MADRE', 'PADRE', 'TUTOR', 'OTRO', name='parentesco'), nullable=False),
    sa.Column('es_contacto_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acudiente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', 'acudiente_id', name='uq_estudiante_acudiente')
    )
    op.create_table('grupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('anio_escolar_id', sa.UUID(), nullable=False),
    sa.Column('profesor_guia_id', sa.UUID(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['profesor_guia_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('anio_escolar_id', sa.UUID(), nullable=False),
    sa.Column('fecha_matricula', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'RETIRADO', 'GRADUADO', 'TRASLADADO', name='estado_matricula'), nullable=False),
    sa.ForeignKeyConstraint(['anio_escolar_id'], ['anios_escolares.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cargo_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'SINPE_MOVIL', 'TARJETA', 'CHEQUE', name='metodo_pago'), nullable=False),
    sa.Column('numero_recibo', sa.String(length=30), nullable=False),
    sa.Column('registrado_por_id', sa.UUID(), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_recibo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('matriculas')
    op.drop_table('grupos')
    op.drop_table('estudiantes_acudientes')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('estudiantes')
    op.drop_table('anios_escolares')
    # ### end Alembic commands ###
