"""agregar identificacion y asignatura a usuarios

Revision ID: b92642b97c68
Revises: 228a0066ed6f
Create Date: 2026-06-16 17:28:30.379703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92642b97c68'
down_revision: Union[str, Sequence[str], None] = '228a0066ed6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('identificacion', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('asignatura', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['identificacion'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'asignatura')
    op.drop_column('usuarios', 'identificacion')
    # ### end Alembic commands ###
